moddedLootInChests = true
extractinatorSupport = true
techLoot = "MODERN_INDUSTRIALIZATION"

[defaultCabin]
minHeight = 6
maxHeight = 42

[deepslateCabin]
minHeight = -56
maxHeight = -6

[desertCabin]
minHeight = 6
maxHeight = 44

[mesaCabin]
minHeight = 6
maxHeight = 48

[taigaCabin]
minHeight = 6
maxHeight = 48

[iceCabin]
minHeight = 6
maxHeight = 42

[jungleCabin]
minHeight = 6
maxHeight = 44

[oceanCabin]
minHeight = 24
maxHeight = 44
